STORAGE_STATE_PATH = "tiktok_auth.json"

DEFAULT_SEARCH_QUERY = "cats"  # You can change this to any search term

DEFAULT_SKIP_PERCENT = 12
MIN_WATCH_DURATION_SECONDS = 5
MAX_WATCH_DURATION_SECONDS = 15
MAX_FEED_SCROLLS = 10
MAX_VIDEOS_TO_PROCESS = 50
